adequate_passwords.settings:
  type: config_object
  mapping:
    strength:
      type: integer
      label: 'Minimum password strength'
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
        label: 'Role'
